module

public import Veir.Dominance.Block
public import Veir.Dominance.Projection
public import Veir.Interfaces.RegionKindInterfaces

/-!
# Propositional Operation Dominance Lemmas

Lemmas about operation-first MLIR dominance generated by lexical order, block
dominance, graph-region semantics, and the operation/region hierarchy. The
definitions live in `Veir.Dominance.Basic`.

Unlike block dominance, operation dominance is not globally transitive under
LLVM/MLIR's unreachable-block convention: dominance between distinct
unreachable blocks must not erase lexical order inside either block.
-/

public section

namespace Veir

variable {OpInfo : Type} [HasOpInfo OpInfo]
variable {ctx : WfIRContext OpInfo}

/-- An operation with a recorded parent block is in bounds. -/
@[grind →]
theorem OperationPtr.inBounds_of_parent_eq_some
    {op : OperationPtr} {block : BlockPtr} {ctx : IRContext OpInfo}
    (parentEq : (op.get! ctx).parent = some block) :
    op.InBounds ctx := by
  apply Classical.byContradiction
  intro opOutOfBounds
  have opDefault : op.get! ctx = default :=
    OperationPtr.get!_of_not_inBounds opOutOfBounds
  rw [opDefault] at parentEq
  contradiction

/-- An operation with a recorded lexical successor is in bounds. -/
theorem OperationPtr.inBounds_of_next_eq_some
    {op next : OperationPtr} {ctx : IRContext OpInfo}
    (nextEq : (op.get! ctx).next = some next) :
    op.InBounds ctx := by
  apply Classical.byContradiction
  intro opOutOfBounds
  have opDefault : op.get! ctx = default :=
    OperationPtr.get!_of_not_inBounds opOutOfBounds
  rw [opDefault] at nextEq
  contradiction

/-- A proper operation ancestor of an operation is also an ancestor of its successor. -/
theorem IRNode.ProperAncestor.operation_next
    {ancestor middle target : OperationPtr}
    (ancestry :
      IRNode.ProperAncestor (.operation ancestor) (.operation middle) ctx)
    (nextEq : (middle.get! ctx.raw).next = some target) :
    IRNode.Ancestor (.operation ancestor) (.operation target) ctx := by
  obtain ⟨nodes, path⟩ := ancestry.toAncestor.exists_parentPath
  cases path with
  | single => exact False.elim (ancestry.ne rfl)
  | @cons _ parent nodes immediate tail =>
      cases parent with
      | operation parent => simp [IRNode.parent!] at immediate
      | region parent => simp [IRNode.parent!] at immediate
      | block block =>
          have middleParent : (middle.get! ctx.raw).parent = some block := by
            simpa [IRNode.parent!] using immediate
          have middleInBounds := OperationPtr.inBounds_of_parent_eq_some middleParent
          obtain ⟨operations, chain⟩ := ctx.wellFormed.opChain block (by grind)
          have targetParent := chain.parent!_nextOp_eq middleInBounds middleParent nextEq
          exact .of_parentPath (.cons (by simpa [IRNode.parent!] using targetParent) tail)

/-- A distinct operation ancestor of an operation is also an ancestor of its successor. -/
theorem IRNode.Ancestor.operation_next_of_ne
    {ancestor middle target : OperationPtr}
    (ancestry : IRNode.Ancestor (.operation ancestor) (.operation middle) ctx)
    (ancestorNeMiddle : ancestor ≠ middle)
    (nextEq : (middle.get! ctx.raw).next = some target) :
    IRNode.Ancestor (.operation ancestor) (.operation target) ctx :=
  (IRNode.ProperAncestor.of_ancestor_ne ancestry
    (by simpa using ancestorNeMiddle)).operation_next nextEq

/-- A proper operation ancestor of an operation is also an ancestor of its predecessor. -/
theorem IRNode.ProperAncestor.operation_previous
    {ancestor previous target : OperationPtr}
    (ancestry :
      IRNode.ProperAncestor (.operation ancestor) (.operation target) ctx)
    (nextEq : (previous.get! ctx.raw).next = some target) :
    IRNode.Ancestor (.operation ancestor) (.operation previous) ctx := by
  obtain ⟨nodes, path⟩ := ancestry.toAncestor.exists_parentPath
  cases path with
  | single => exact False.elim (ancestry.ne rfl)
  | @cons _ parent nodes immediate tail =>
      cases parent with
      | operation parent => simp [IRNode.parent!] at immediate
      | region parent => simp [IRNode.parent!] at immediate
      | block block =>
          have targetParent : (target.get! ctx.raw).parent = some block := by
            simpa [IRNode.parent!] using immediate
          have targetInBounds := OperationPtr.inBounds_of_parent_eq_some targetParent
          have previousInBounds := OperationPtr.inBounds_of_next_eq_some nextEq
          have previousEq : (target.get! ctx.raw).prev = some previous :=
            ctx.wellFormed.OperationPtr_prev!_eq_some_of_next!_eq_some
              previousInBounds nextEq
          obtain ⟨operations, chain⟩ := ctx.wellFormed.opChain block (by grind)
          have previousParent :=
            chain.parent!_prevOp_eq targetInBounds targetParent previousEq
          exact .of_parentPath (.cons (by simpa [IRNode.parent!] using previousParent) tail)

/-- A distinct operation ancestor of an operation is also an ancestor of its predecessor. -/
theorem IRNode.Ancestor.operation_previous_of_ne
    {ancestor previous target : OperationPtr}
    (ancestry : IRNode.Ancestor (.operation ancestor) (.operation target) ctx)
    (ancestorNeTarget : ancestor ≠ target)
    (nextEq : (previous.get! ctx.raw).next = some target) :
    IRNode.Ancestor (.operation ancestor) (.operation previous) ctx :=
  (IRNode.ProperAncestor.of_ancestor_ne ancestry
    (by simpa using ancestorNeTarget)).operation_previous nextEq

/-- A proper operation ancestor of an operation is an ancestor of its block. -/
theorem IRNode.ProperAncestor.operation_block
    {ancestor descendant : OperationPtr} {block : BlockPtr}
    (ancestry :
      IRNode.ProperAncestor (.operation ancestor) (.operation descendant) ctx)
    (descendantParent : (descendant.get! ctx.raw).parent = some block) :
    IRNode.Ancestor (.operation ancestor) (.block block) ctx := by
  obtain ⟨nodes, path⟩ := ancestry.toAncestor.exists_parentPath
  cases path with
  | single => exact False.elim (ancestry.ne rfl)
  | @cons _ parent nodes immediate tail =>
      cases parent with
      | operation parent => simp [IRNode.parent!] at immediate
      | region parent => simp [IRNode.parent!] at immediate
      | block parentBlock =>
          have recordedParent : (descendant.get! ctx.raw).parent = some parentBlock := by
            simpa [IRNode.parent!] using immediate
          have blockEq : parentBlock = block :=
            Option.some.inj (recordedParent.symm.trans descendantParent)
          subst parentBlock
          exact .of_parentPath tail

/-- A distinct operation ancestor of an operation is an ancestor of its block. -/
theorem IRNode.Ancestor.operation_block_of_ne
    {ancestor descendant : OperationPtr} {block : BlockPtr}
    (ancestry : IRNode.Ancestor (.operation ancestor) (.operation descendant) ctx)
    (ancestorNeDescendant : ancestor ≠ descendant)
    (descendantParent : (descendant.get! ctx.raw).parent = some block) :
    IRNode.Ancestor (.operation ancestor) (.block block) ctx :=
  (IRNode.ProperAncestor.of_ancestor_ne ancestry
    (by simpa using ancestorNeDescendant)).operation_block descendantParent

/-- An operation ancestor of one block is an ancestor of every block in that region. -/
theorem IRNode.Ancestor.block_of_same_region
    {ancestor : OperationPtr} {left right : BlockPtr} {region : RegionPtr}
    (ancestry : IRNode.Ancestor (.operation ancestor) (.block left) ctx)
    (leftParent : (left.get! ctx.raw).parent = some region)
    (rightParent : (right.get! ctx.raw).parent = some region) :
    IRNode.Ancestor (.operation ancestor) (.block right) ctx := by
  obtain ⟨nodes, path⟩ := ancestry.exists_parentPath
  cases path with
  | @cons _ parent nodes immediate tail =>
      cases parent with
      | operation parent => simp [IRNode.parent!] at immediate
      | block parent => simp [IRNode.parent!] at immediate
      | region parentRegion =>
          have recordedParent : (left.get! ctx.raw).parent = some parentRegion := by
            simpa [IRNode.parent!] using immediate
          have regionEq : parentRegion = region :=
            Option.some.inj (recordedParent.symm.trans leftParent)
          subst parentRegion
          exact .of_parentPath
            (.cons (by simpa [IRNode.parent!] using rightParent) tail)

namespace OperationPtr.DominatesInRegion

variable {source target : OperationPtr} {region : RegionPtr}

/-- The target of region-local dominance is directly contained in that region. -/
theorem target_parent
    (dominance : source.DominatesInRegion target region ctx) :
    ∃ block,
      (target.get! ctx.raw).parent = some block ∧
      (block.get! ctx.raw).parent = some region := by
  cases dominance with
  | ssa dominance =>
      cases dominance with
      | block dominance =>
          obtain ⟨_, targetParent, blockParent, _, _⟩ := dominance
          exact ⟨_, targetParent, blockParent⟩
      | blocks _ _ _ targetRegion _ _ _ =>
          exact OperationPtr.getParentRegion!_eq_some_iff.mp targetRegion
  | graph dominance =>
      cases dominance with
      | all _ targetRegion _ =>
          exact OperationPtr.getParentRegion!_eq_some_iff.mp targetRegion

/-- An operation directly contained in a region dominates itself there. -/
theorem refl
    {block : BlockPtr}
    (sourceParent : (source.get! ctx.raw).parent = some block)
    (blockParent : (block.get! ctx.raw).parent = some region) :
    source.DominatesInRegion source region ctx := by
  have parentRegion : source.getParentRegion! ctx.raw = some region :=
    OperationPtr.getParentRegion!_eq_some_iff.mpr
      ⟨block, sourceParent, blockParent⟩
  cases regionSSA : region.hasSSADominance ctx with
  | false =>
      exact .graph (.all parentRegion parentRegion regionSSA)
  | true =>
      exact .ssa (.block
        ⟨sourceParent, sourceParent, blockParent, regionSSA, Nat.le_refl _⟩)

/-- Region-local dominance extends to an immediate lexical successor. -/
theorem next
    {middle target : OperationPtr}
    (dominance : source.DominatesInRegion middle region ctx)
    (nextEq : (middle.get! ctx.raw).next = some target) :
    source.DominatesInRegion target region ctx := by
  obtain ⟨middleBlock, middleParent, blockParent⟩ := dominance.target_parent
  have middleInBounds := OperationPtr.inBounds_of_parent_eq_some middleParent
  obtain ⟨operations, chain⟩ :=
    ctx.wellFormed.opChain middleBlock (by grind)
  have targetParent := chain.parent!_nextOp_eq middleInBounds middleParent nextEq
  have targetRegion : target.getParentRegion! ctx.raw = some region :=
    OperationPtr.getParentRegion!_eq_some_iff.mpr
      ⟨middleBlock, targetParent, blockParent⟩
  cases dominance with
  | ssa dominance =>
      cases dominance with
      | block dominance =>
          obtain ⟨sourceParent, recordedMiddleParent, _, regionSSA, indexLe⟩ :=
            dominance
          have indexNext := OperationPtr.idxInParent_next_eq middle ctx.raw target
            nextEq (OperationPtr.inBounds_of_parent_eq_some targetParent)
            middleInBounds ctx.wellFormed
          have blockEq := Option.some.inj (recordedMiddleParent.symm.trans middleParent)
          subst middleBlock
          exact .ssa (.block
            ⟨sourceParent, targetParent, blockParent, regionSSA, by omega⟩)
      | blocks sourceParent recordedMiddleParent sourceRegion middleRegion regionSSA
          blocksNe blockDominance =>
          have blockEq := Option.some.inj (recordedMiddleParent.symm.trans middleParent)
          subst middleBlock
          exact .ssa (.blocks sourceParent targetParent sourceRegion targetRegion
            regionSSA blocksNe blockDominance)
  | graph dominance =>
      cases dominance with
      | all sourceRegion _ regionGraph =>
          exact .graph (.all sourceRegion targetRegion regionGraph)

/-- A strict region-local dominator also dominates an immediate predecessor. -/
theorem previous
    {previous target : OperationPtr}
    (dominance : source.DominatesInRegion target region ctx)
    (sourceNeTarget : source ≠ target)
    (nextEq : (previous.get! ctx.raw).next = some target) :
    source.DominatesInRegion previous region ctx := by
  obtain ⟨targetBlock, targetParent, blockParent⟩ := dominance.target_parent
  have targetInBounds := OperationPtr.inBounds_of_parent_eq_some targetParent
  have previousInBounds := OperationPtr.inBounds_of_next_eq_some nextEq
  have previousEq : (target.get! ctx.raw).prev = some previous :=
    ctx.wellFormed.OperationPtr_prev!_eq_some_of_next!_eq_some
      previousInBounds nextEq
  obtain ⟨operations, chain⟩ :=
    ctx.wellFormed.opChain targetBlock (by grind)
  have previousParent :=
    chain.parent!_prevOp_eq targetInBounds targetParent previousEq
  have previousRegion : previous.getParentRegion! ctx.raw = some region :=
    OperationPtr.getParentRegion!_eq_some_iff.mpr
      ⟨targetBlock, previousParent, blockParent⟩
  cases dominance with
  | ssa dominance =>
      cases dominance with
      | block dominance =>
          obtain ⟨sourceParent, recordedTargetParent, _, regionSSA, indexLe⟩ :=
            dominance
          have blockEq := Option.some.inj (recordedTargetParent.symm.trans targetParent)
          subst targetBlock
          have indexNext := OperationPtr.idxInParent_next_eq previous ctx.raw target
            nextEq targetInBounds previousInBounds ctx.wellFormed
          have indexNe : source.idxInParent ctx.raw ≠ target.idxInParent ctx.raw := by
            intro indexEq
            exact sourceNeTarget (OperationPtr.eq_of_idxInParent_eq
              sourceParent targetParent (indexEq := indexEq))
          exact .ssa (.block
            ⟨sourceParent, previousParent, blockParent, regionSSA, by omega⟩)
      | blocks sourceParent recordedTargetParent sourceRegion targetRegion regionSSA
          blocksNe blockDominance =>
          have blockEq := Option.some.inj (recordedTargetParent.symm.trans targetParent)
          subst targetBlock
          exact .ssa (.blocks sourceParent previousParent sourceRegion previousRegion
            regionSSA blocksNe blockDominance)
  | graph dominance =>
      cases dominance with
      | all sourceRegion _ regionGraph =>
          exact .graph (.all sourceRegion previousRegion regionGraph)

end OperationPtr.DominatesInRegion

namespace OperationPtr.BlockEntryDominance

variable {source : OperationPtr} {target predecessor : BlockPtr}
variable {region : RegionPtr}

/-- Entry dominance also dominates the end of the same block. -/
theorem toEnd (dominance : source.BlockEntryDominance target ctx) :
    source.BlockEndDominance target ctx := by
  cases dominance with
  | ssa sourceParent sourceBlockParent targetParent regionSSA blocksNe blockDominance =>
      exact .ssa sourceParent sourceBlockParent targetParent regionSSA blocksNe blockDominance
  | graph sourceParent sourceBlockParent targetParent regionGraph =>
      exact .graph sourceParent sourceBlockParent targetParent regionGraph
  | ancestor localDominance ancestry => exact .ancestor localDominance ancestry

/-- Entry dominance propagates to the end of an immediate CFG predecessor. -/
theorem atPredecessorEnd
    (dominance : source.BlockEntryDominance target ctx)
    (predecessorParent : (predecessor.get! ctx.raw).parent = some region)
    (targetParent : (target.get! ctx.raw).parent = some region)
    (successorEdge : target ∈ predecessor.getSuccessors! ctx.raw) :
    source.BlockEndDominance predecessor ctx := by
  cases dominance with
  | @ssa sourceBlock recordedRegion sourceParent sourceBlockParent
      recordedTargetParent regionSSA blocksNe blockDominance =>
      have regionEq : recordedRegion = region := by grind
      subst recordedRegion
      have sourceDominatesPredecessor :=
        BlockPtr.Dominates.predecessor_of_dominates_successor
          sourceBlockParent predecessorParent targetParent blocksNe successorEdge
          blockDominance
      by_cases blockEq : sourceBlock = predecessor
      · subst sourceBlock
        exact .same sourceParent
      · exact .ssa sourceParent sourceBlockParent predecessorParent regionSSA
          blockEq sourceDominatesPredecessor
  | @graph sourceBlock recordedRegion sourceParent sourceBlockParent
      recordedTargetParent regionGraph =>
      have regionEq : recordedRegion = region := by grind
      subst recordedRegion
      exact .graph sourceParent sourceBlockParent predecessorParent regionGraph
  | @ancestor ancestor localRegion localDominance ancestry =>
      exact .ancestor localDominance
        (ancestry.block_of_same_region targetParent predecessorParent)

end OperationPtr.BlockEntryDominance

namespace OperationPtr.BlockEndDominance

variable {source : OperationPtr} {target : BlockPtr}

/-- An empty block cannot contain the source of same-block end dominance. -/
theorem toEntry_of_first_eq_none
    (dominance : source.BlockEndDominance target ctx)
    (firstEq : (target.get! ctx.raw).firstOp = none) :
    source.BlockEntryDominance target ctx := by
  cases dominance with
  | same sourceParent =>
      have sourceInBounds := OperationPtr.inBounds_of_parent_eq_some sourceParent
      obtain ⟨operations, chain⟩ := ctx.wellFormed.opChain target (by grind)
      have sourceMem : source ∈ operations := by grind [BlockPtr.OpChain]
      have operationsNe : operations ≠ #[] := by grind
      have := chain.first
      grind
  | ssa sourceParent sourceBlockParent targetParent regionSSA blocksNe
      blockDominance =>
      exact .ssa sourceParent sourceBlockParent targetParent regionSSA blocksNe
        blockDominance
  | graph sourceParent sourceBlockParent targetParent regionGraph =>
      exact .graph sourceParent sourceBlockParent targetParent regionGraph
  | ancestor localDominance ancestry => exact .ancestor localDominance ancestry

end OperationPtr.BlockEndDominance

namespace OperationPtr.BlockEntryDominance

variable {source first : OperationPtr} {target : BlockPtr}

/-- The block relation's SSA case is structural block-entry dominance. -/
theorem of_blocks {sourceBlock : BlockPtr} {region : RegionPtr}
    (sourceParent : (source.get! ctx.raw).parent = some sourceBlock)
    (sourceRegion : source.getParentRegion ctx.raw = some region)
    (targetParent : (target.get! ctx.raw).parent = some region)
    (regionSSA : region.hasSSADominance ctx = true)
    (blocksNe : sourceBlock ≠ target)
    (blockDominance : sourceBlock.Dominates target ctx) :
    source.BlockEntryDominance target ctx := by
  obtain ⟨recordedSourceBlock, recordedSourceParent, sourceBlockParent⟩ :=
    (OperationPtr.getParentRegion_eq_some_iff
      (opInBounds := OperationPtr.inBounds_of_parent_eq_some sourceParent)
      (ctxWellFormed := ctx.wellFormed)).mp sourceRegion
  have sourceBlockEq : recordedSourceBlock = sourceBlock :=
    Option.some.inj (recordedSourceParent.symm.trans sourceParent)
  subst recordedSourceBlock
  exact .ssa sourceParent sourceBlockParent targetParent regionSSA blocksNe
    blockDominance

/-- The block relation's graph case is structural block-entry dominance. -/
theorem of_graph {sourceBlock : BlockPtr} {region : RegionPtr}
    (sourceParent : (source.get! ctx.raw).parent = some sourceBlock)
    (sourceRegion : source.getParentRegion ctx.raw = some region)
    (targetParent : (target.get! ctx.raw).parent = some region)
    (regionGraph : region.hasSSADominance ctx = false) :
    source.BlockEntryDominance target ctx := by
  obtain ⟨recordedSourceBlock, recordedSourceParent, sourceBlockParent⟩ :=
    (OperationPtr.getParentRegion_eq_some_iff
      (opInBounds := OperationPtr.inBounds_of_parent_eq_some sourceParent)
      (ctxWellFormed := ctx.wellFormed)).mp sourceRegion
  have sourceBlockEq : recordedSourceBlock = sourceBlock :=
    Option.some.inj (recordedSourceParent.symm.trans sourceParent)
  subst recordedSourceBlock
  exact .graph sourceParent sourceBlockParent targetParent regionGraph

/-- Strict dominance of a block's first operation is block-entry dominance. -/
theorem of_strictlyDominates_first
    (dominance : source.Dominates first ctx)
    (sourceNeFirst : source ≠ first)
    (firstParent : (first.get! ctx.raw).parent = some target)
    (firstEq : (target.get! ctx.raw).firstOp = some first) :
    source.BlockEntryDominance target ctx := by
  rcases dominance with sourceEq |
      ⟨localRegion, ancestor, ancestry, localDominance⟩
  · exact False.elim (sourceNeFirst sourceEq)
  · by_cases ancestorEq : ancestor = first
    · subst ancestor
      cases localDominance with
      | ssa ssaDominance =>
          cases ssaDominance with
          | block blockDominance =>
              obtain ⟨sourceParent, recordedFirstParent, _, regionSSA, indexLe⟩ :=
                blockDominance
              have blockEq := Option.some.inj
                (recordedFirstParent.symm.trans firstParent)
              subst_vars
              have firstIndex : first.idxInParent ctx.raw = 0 :=
                OperationPtr.idxInParent_eq_zero_of_firstOp_eq firstParent firstEq
              have indexEq : source.idxInParent ctx.raw = first.idxInParent ctx.raw := by
                omega
              exact False.elim (sourceNeFirst
                (OperationPtr.eq_of_idxInParent_eq sourceParent firstParent
                  (indexEq := indexEq)))
          | blocks sourceParent recordedFirstParent sourceRegion firstRegion
              regionSSA blocksNe cfgDominance =>
              rename_i sourceBlock targetBlock
              have targetBlockEq : targetBlock = target :=
                Option.some.inj (recordedFirstParent.symm.trans firstParent)
              subst targetBlock
              obtain ⟨recordedSourceBlock, recordedSourceParent,
                sourceBlockParent⟩ :=
                OperationPtr.getParentRegion!_eq_some_iff.mp sourceRegion
              have sourceBlockEq : recordedSourceBlock = sourceBlock :=
                Option.some.inj (recordedSourceParent.symm.trans sourceParent)
              subst recordedSourceBlock
              obtain ⟨recordedTargetBlock, recordedTargetParent,
                targetParent⟩ :=
                OperationPtr.getParentRegion!_eq_some_iff.mp firstRegion
              have recordedTargetBlockEq : recordedTargetBlock = target :=
                Option.some.inj (recordedTargetParent.symm.trans firstParent)
              subst recordedTargetBlock
              exact .ssa sourceParent sourceBlockParent targetParent regionSSA
                blocksNe cfgDominance
      | graph graphDominance =>
          cases graphDominance with
          | all sourceRegion firstRegion regionGraph =>
              obtain ⟨recordedSourceBlock, recordedSourceParent,
                sourceBlockParent⟩ :=
                OperationPtr.getParentRegion!_eq_some_iff.mp sourceRegion
              obtain ⟨recordedTargetBlock, recordedTargetParent,
                targetParent⟩ :=
                OperationPtr.getParentRegion!_eq_some_iff.mp firstRegion
              have recordedTargetBlockEq : recordedTargetBlock = target :=
                Option.some.inj (recordedTargetParent.symm.trans firstParent)
              subst recordedTargetBlock
              exact .graph recordedSourceParent sourceBlockParent targetParent regionGraph
    · have properAncestry :
          (IRNode.operation ancestor).ProperAncestor (.operation first) ctx :=
        .of_ancestor_ne ancestry (by simpa using ancestorEq)
      exact .ancestor localDominance
        (properAncestry.operation_block firstParent)

end OperationPtr.BlockEntryDominance

namespace OperationPtr.HierarchicallyReachable

/-- Hierarchical reachability includes reachability from the containing region's entry. -/
@[grind →]
theorem reachableFromEntry
    {ctx : WfIRContext OpInfo} {target : OperationPtr}
    (reachable : target.HierarchicallyReachable ctx) :
    target.ReachableFromEntry ctx :=
  reachable.1

/-- Every dominator of a hierarchically reachable operation is reachable from entry. -/
@[grind →]
theorem dominatorReachableFromEntry
    {ctx : WfIRContext OpInfo} {source target : OperationPtr}
    (reachable : target.HierarchicallyReachable ctx)
    (dominance : source.Dominates target ctx) :
    source.ReachableFromEntry ctx :=
  reachable.2.2 source dominance

end OperationPtr.HierarchicallyReachable

/-- Dominance extends to an immediate lexical successor in an attached block. -/
theorem OperationPtr.dominates_next
    {source middle target : OperationPtr} {block : BlockPtr}
    (dominance : source.Dominates middle ctx)
    (middleParent : (middle.get! ctx.raw).parent = some block)
    (blockParent : (block.get! ctx.raw).parent = some region)
    (nextEq : (middle.get! ctx.raw).next = some target) :
    source.Dominates target ctx := by
  rcases dominance with rfl |
      ⟨sourceRegion, ancestor, ancestry, localDominance⟩
  · exact Or.inr
      ⟨region, target, .refl,
        (OperationPtr.DominatesInRegion.refl middleParent blockParent).next nextEq⟩
  · by_cases ancestorEq : ancestor = middle
    · subst ancestor
      exact Or.inr
        ⟨sourceRegion, target, .refl, localDominance.next nextEq⟩
    · exact Or.inr ⟨sourceRegion, ancestor,
        (IRNode.ProperAncestor.of_ancestor_ne ancestry
          (by simpa using ancestorEq)).operation_next nextEq,
        localDominance⟩

/-- A strict dominator also dominates an immediate lexical predecessor. -/
theorem OperationPtr.dominates_previous
    {source previous target : OperationPtr}
    (dominance : source.StrictlyDominates target ctx)
    (nextEq : (previous.get! ctx.raw).next = some target) :
    source.Dominates previous ctx := by
  rcases dominance.1 with sourceEq |
      ⟨region, ancestor, ancestry, localDominance⟩
  · exact False.elim (dominance.2 sourceEq)
  · by_cases ancestorEq : ancestor = target
    · subst ancestor
      exact Or.inr ⟨region, previous, .refl,
        localDominance.previous dominance.2 nextEq⟩
    · exact Or.inr ⟨region, ancestor,
        (IRNode.ProperAncestor.of_ancestor_ne ancestry
          (by simpa using ancestorEq)).operation_previous nextEq,
        localDominance⟩

namespace BlockPtr.OpChain

variable {block : BlockPtr} {operations : Array OperationPtr}

/-- Earlier operations in an attached well-formed block dominate later operations. -/
theorem dominates_getElem_of_le
    (chain : BlockPtr.OpChain block ctx.raw operations)
    (blockParent : (block.get! ctx.raw).parent = some region)
    {i j : Nat} (iInBounds : i < operations.size)
    (jInBounds : j < operations.size) (indexLe : i ≤ j) :
    operations[i].Dominates operations[j] ctx := by
  induction indexLe with
  | refl => exact Or.inl rfl
  | @step j indexLe inductionHypothesis =>
      have jInBounds' : j < operations.size := Nat.lt_of_succ_lt jInBounds
      have nextEq :
          (operations[j].get! ctx.raw).next = some operations[j + 1] := by
        have := chain.next jInBounds'
        rw [Array.getElem?_eq_getElem (by grind)] at this
        simpa using this
      exact OperationPtr.dominates_next
        (inductionHypothesis jInBounds') (chain.opParent (by grind))
        blockParent nextEq

/-- A dominator of one operation in an attached block dominates every later operation. -/
theorem dominates_getElem_of_le_of_dominates
    (chain : BlockPtr.OpChain block ctx.raw operations)
    (blockParent : (block.get! ctx.raw).parent = some region)
    {source : OperationPtr} {i j : Nat}
    (iInBounds : i < operations.size)
    (jInBounds : j < operations.size) (indexLe : i ≤ j)
    (sourceDominance : source.Dominates operations[i] ctx) :
    source.Dominates operations[j] ctx := by
  induction indexLe with
  | refl => exact sourceDominance
  | @step j indexLe inductionHypothesis =>
      have jInBounds' : j < operations.size := Nat.lt_of_succ_lt jInBounds
      have nextEq :
          (operations[j].get! ctx.raw).next = some operations[j + 1] := by
        have := chain.next jInBounds'
        rw [Array.getElem?_eq_getElem (by grind)] at this
        simpa using this
      exact OperationPtr.dominates_next
        (inductionHypothesis jInBounds') (chain.opParent (by grind))
        blockParent nextEq

end BlockPtr.OpChain

namespace OperationPtr

variable {source middle target projection : OperationPtr}
variable {block : BlockPtr} {region : RegionPtr}

/-- Definition of strict operation dominance. -/
theorem strictlyDominates_def :
    source.StrictlyDominates target ctx ↔
      source.Dominates target ctx ∧ source ≠ target := by
  rfl

/-- Strict dominance implies ordinary dominance. -/
theorem dominates_of_strictlyDominates :
    source.StrictlyDominates target ctx → source.Dominates target ctx := by
  grind [OperationPtr.StrictlyDominates]

/-- Operation dominance is reflexive. -/
@[grind .]
theorem dominates_refl : source.Dominates source ctx :=
  Or.inl rfl

/-- Dominance established inside one region lifts to operation dominance. -/
theorem dominates_of_dominatesInRegion
    (dominance : source.DominatesInRegion target region ctx) :
    source.Dominates target ctx := by
  exact Or.inr ⟨region, target, .refl, dominance⟩

/-- Distinct operations in dominating SSACFG blocks inherit block dominance. -/
theorem dominates_of_blocks
    {sourceBlock targetBlock : BlockPtr}
    (sourceParent : (source.get! ctx.raw).parent = some sourceBlock)
    (targetParent : (target.get! ctx.raw).parent = some targetBlock)
    (sourceBlockParent : (sourceBlock.get! ctx.raw).parent = some region)
    (targetBlockParent : (targetBlock.get! ctx.raw).parent = some region)
    (blocksNe : sourceBlock ≠ targetBlock)
    (blockDominance : sourceBlock.Dominates targetBlock ctx) :
    source.Dominates target ctx := by
  have sourceRegion : source.getParentRegion! ctx.raw = some region := by
    exact OperationPtr.getParentRegion!_eq_some_iff.mpr
      ⟨sourceBlock, sourceParent, sourceBlockParent⟩
  have targetRegion : target.getParentRegion! ctx.raw = some region := by
    exact OperationPtr.getParentRegion!_eq_some_iff.mpr
      ⟨targetBlock, targetParent, targetBlockParent⟩
  by_cases regionSSA : region.hasSSADominance ctx = true
  · exact dominates_of_dominatesInRegion
      (.ssa (.blocks sourceParent targetParent sourceRegion
        targetRegion regionSSA blocksNe blockDominance))
  · have regionGraph : region.hasSSADominance ctx = false := by
      cases regionEq : region.hasSSADominance ctx with
      | false => rfl
      | true => exact False.elim (regionSSA regionEq)
    exact dominates_of_dominatesInRegion
      (.graph (.all sourceRegion targetRegion regionGraph))

/-- Every operation in a graph region dominates every operation in that region. -/
theorem dominates_of_graph
    {sourceBlock targetBlock : BlockPtr}
    (sourceParent : (source.get! ctx.raw).parent = some sourceBlock)
    (targetParent : (target.get! ctx.raw).parent = some targetBlock)
    (sourceBlockParent : (sourceBlock.get! ctx.raw).parent = some region)
    (targetBlockParent : (targetBlock.get! ctx.raw).parent = some region)
    (regionGraph : region.hasSSADominance ctx = false) :
    source.Dominates target ctx := by
  have sourceRegion : source.getParentRegion! ctx.raw = some region := by
    exact OperationPtr.getParentRegion!_eq_some_iff.mpr
      ⟨sourceBlock, sourceParent, sourceBlockParent⟩
  have targetRegion : target.getParentRegion! ctx.raw = some region := by
    exact OperationPtr.getParentRegion!_eq_some_iff.mpr
      ⟨targetBlock, targetParent, targetBlockParent⟩
  exact dominates_of_dominatesInRegion
    (.graph (.all sourceRegion targetRegion regionGraph))

/-- Dominance is either strict dominance or equality. -/
theorem dominates_iff_strictlyDominates_or_eq :
    source.Dominates target ctx ↔
      source.StrictlyDominates target ctx ∨ source = target := by
  constructor
  · intro dominance
    by_cases sourceEq : source = target
    · exact Or.inr sourceEq
    · exact Or.inl ⟨dominance, sourceEq⟩
  · rintro (⟨dominance, _⟩ | rfl)
    · exact dominance
    · exact dominates_refl

/--
If `source` dominates an ancestor of `target` in an enclosing region, it
dominates `target` itself.
-/
theorem dominates_of_ancestorOpInRegion
    (sourceProjection : source.Dominates projection ctx)
    (targetProjection : target.AncestorOpInRegion projection region ctx) :
    source.Dominates target ctx := by
  rcases sourceProjection with rfl |
      ⟨sourceRegion, ancestor, ancestry, dominance⟩
  · obtain ⟨block, projectionParent, blockParent⟩ := targetProjection.parent_region
    exact Or.inr ⟨region, source, targetProjection.isAncestor,
      OperationPtr.DominatesInRegion.refl projectionParent blockParent⟩
  · exact Or.inr ⟨sourceRegion, ancestor,
      ancestry.trans targetProjection.isAncestor, dominance⟩

/--
Region-local dominance of a target ancestor lifts directly to the nested target.
-/
theorem dominates_of_dominatesInRegion_of_ancestorOpInRegion
    (sourceProjection : source.DominatesInRegion projection region ctx)
    (targetProjection : target.AncestorOpInRegion projection region ctx) :
    source.Dominates target ctx :=
  Or.inr ⟨region, projection, targetProjection.isAncestor, sourceProjection⟩

/-- A dominator of an attached block's first operation dominates its last operation. -/
theorem dominates_last_of_first
    {first last : OperationPtr}
    (firstDominance : source.Dominates first ctx)
    (blockParent : (block.get! ctx.raw).parent = some region)
    (firstEq : (block.get! ctx.raw).firstOp = some first)
    (lastEq : (block.get! ctx.raw).lastOp = some last) :
    source.Dominates last ctx := by
  have blockInBounds : block.InBounds ctx.raw := by
    apply Classical.byContradiction
    intro blockOutOfBounds
    have blockDefault : block.get! ctx.raw = default :=
      BlockPtr.get!_of_not_inBounds blockOutOfBounds
    rw [blockDefault] at firstEq
    contradiction
  obtain ⟨operations, chain⟩ := ctx.wellFormed.opChain block blockInBounds
  have firstMem : first ∈ operations := by
    have firstParent := chain.parent!_firstOp_eq firstEq
    grind [BlockPtr.OpChain]
  have lastMem : last ∈ operations := by
    have lastParent := chain.parent!_lastOp_eq lastEq
    grind [BlockPtr.OpChain]
  obtain ⟨firstIndex, firstIndexInBounds, firstAtIndex⟩ :=
    Array.getElem_of_mem firstMem
  obtain ⟨lastIndex, lastIndexInBounds, lastAtIndex⟩ :=
    Array.getElem_of_mem lastMem
  have firstIndexEq : firstIndex = 0 := by
    have firstOption := chain.first
    rw [firstEq] at firstOption
    have zeroInBounds : 0 < operations.size := by grind
    rw [Array.getElem?_eq_getElem zeroInBounds] at firstOption
    have zeroAtIndex : operations[0] = first := Option.some.inj firstOption.symm
    apply Classical.byContradiction
    intro indexNe
    apply (BlockPtr.OpChain_array_injective chain firstIndex 0
      firstIndexInBounds zeroInBounds indexNe)
    rw [firstAtIndex, zeroAtIndex]
  have finalIndexInBounds : operations.size - 1 < operations.size := by grind
  have lastAtFinalIndex : operations[operations.size - 1] = last := by
    have lastOption : operations[operations.size - 1]? = some last := by
      rw [← chain.last]
      exact lastEq
    rw [Array.getElem?_eq_getElem finalIndexInBounds] at lastOption
    exact Option.some.inj lastOption
  have lastIndexEq : lastIndex = operations.size - 1 := by
    apply Classical.byContradiction
    intro indexNe
    apply (BlockPtr.OpChain_array_injective chain lastIndex
      (operations.size - 1) lastIndexInBounds finalIndexInBounds indexNe)
    rw [lastAtIndex, lastAtFinalIndex]
  have indexLe : firstIndex ≤ lastIndex := by
    rw [firstIndexEq, lastIndexEq]
    omega
  rw [← firstAtIndex] at firstDominance
  rw [← lastAtIndex]
  exact chain.dominates_getElem_of_le_of_dominates
    blockParent firstIndexInBounds lastIndexInBounds indexLe firstDominance

/-- Every operation in an attached block dominates that block's last operation. -/
theorem dominates_last
    (sourceParent : (source.get! ctx.raw).parent = some block)
    (blockParent : (block.get! ctx.raw).parent = some region)
    (lastEq : (block.get! ctx.raw).lastOp = some target) :
    source.Dominates target ctx := by
  have sourceInBounds : source.InBounds ctx.raw := by
    apply Classical.byContradiction
    intro sourceOutOfBounds
    have sourceDefault : source.get! ctx.raw = default :=
      get!_of_not_inBounds sourceOutOfBounds
    rw [sourceDefault] at sourceParent
    contradiction
  have blockInBounds : block.InBounds ctx.raw := by grind
  obtain ⟨operations, chain⟩ := ctx.wellFormed.opChain block blockInBounds
  have sourceMem : source ∈ operations := by
    grind [BlockPtr.OpChain]
  have targetMem : target ∈ operations := by
    have targetInBounds : target.InBounds ctx.raw := by grind
    have targetParent := chain.parent!_lastOp_eq lastEq
    grind [BlockPtr.OpChain]
  obtain ⟨sourceIndex, sourceIndexInBounds, sourceAtIndex⟩ :=
    Array.getElem_of_mem sourceMem
  obtain ⟨targetIndex, targetIndexInBounds, targetAtIndex⟩ :=
    Array.getElem_of_mem targetMem
  have lastIndexInBounds : operations.size - 1 < operations.size := by grind
  have lastAtIndex : operations[operations.size - 1] = target := by
    have lastOption : operations[operations.size - 1]? = some target := by
      rw [← chain.last]
      exact lastEq
    rw [Array.getElem?_eq_getElem lastIndexInBounds] at lastOption
    exact Option.some.inj lastOption
  have targetIndexEq : targetIndex = operations.size - 1 := by
    apply Classical.byContradiction
    intro indexNe
    apply (BlockPtr.OpChain_array_injective chain targetIndex
      (operations.size - 1) targetIndexInBounds lastIndexInBounds indexNe)
    rw [targetAtIndex, lastAtIndex]
  have indexLe : sourceIndex ≤ targetIndex := by
    rw [targetIndexEq]
    grind
  rw [← sourceAtIndex, ← targetAtIndex]
  exact chain.dominates_getElem_of_le
    blockParent sourceIndexInBounds targetIndexInBounds indexLe

/-- Structural dominance of a block end dominates its last operation. -/
theorem BlockEndDominance.dominates_last
    (dominance : source.BlockEndDominance block ctx)
    (blockParent : (block.get! ctx.raw).parent = some region)
    (lastEq : (block.get! ctx.raw).lastOp = some target) :
    source.Dominates target ctx := by
  have blockInBounds : block.InBounds ctx.raw := by
    apply Classical.byContradiction
    intro blockOutOfBounds
    have blockDefault : block.get! ctx.raw = default :=
      BlockPtr.get!_of_not_inBounds blockOutOfBounds
    rw [blockDefault] at lastEq
    contradiction
  obtain ⟨operations, chain⟩ := ctx.wellFormed.opChain block blockInBounds
  have targetParent := chain.parent!_lastOp_eq lastEq
  cases dominance with
  | same sourceParent =>
      exact OperationPtr.dominates_last sourceParent blockParent lastEq
  | ssa sourceParent sourceBlockParent blockParent _ blocksNe blockDominance =>
      exact OperationPtr.dominates_of_blocks sourceParent targetParent
        sourceBlockParent blockParent blocksNe blockDominance
  | graph sourceParent sourceBlockParent blockParent regionGraph =>
      exact OperationPtr.dominates_of_graph sourceParent targetParent
        sourceBlockParent blockParent regionGraph
  | @ancestor ancestor region localDominance ancestry =>
      have blockAncestor : (IRNode.block block).Ancestor (.operation target) ctx :=
        IRNode.Ancestor.of_parent (by
          simpa [IRNode.parent!] using targetParent)
      exact Or.inr
        ⟨region, ancestor, ancestry.trans blockAncestor, localDominance⟩

end OperationPtr

end Veir
