name = "VeIR"
version = "0.1.0"
defaultTargets = ["buffed-benchmark"]
moreLeanArgs = ["--tstack=400000"]
moreServerArgs = ["--tstack=400000"]
moreLeancArgs = ["-flto=full"]
moreLinkArgs = ["-flto=full"]

[[require]]
name = "ExArray"
path = "ExArray"

[[lean_lib]]
name = "Veir"
root = "BuffedBenchmark"

[[lean_exe]]
name = "buffed-benchmark"
root = "BuffedBenchmark"
# moreLeancArgs = ["-g", "-O0"]
