module

import Veir.Interfaces.FunctionInterfaces
import Veir.Interfaces.RegionKindInterfaces
import Veir.Interfaces.SideEffectInterfaces
import Veir.Interfaces.DeadCodeInterfaces
import Veir.Interfaces.ConstantLikeInterfaces
