-- AUTOGENERATED Veir file: Automated GlobalISel pattern translation from llvm-project/llvm/include/llvm/Target/GlobalISel/Combine.td. Commit c86dd0703982b39cacf12cd044ab9735f31d1e1d

import Veir.Pass
import Veir.PatternRewriter.Basic
import Veir.Passes.Matching

namespace Veir.RISCV

def sub_minus_one (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (lhs, op1, _props) := matchSub op rewriter.ctx | return rewriter
  let some cst := matchConstantIntVal lhs rewriter.ctx | return rewriter
  if cst.value ≠ -1 then return rewriter
  let .integerType ctype := (op1.getType! rewriter.ctx.raw).val | return rewriter
  let cstOpProp := LLVMConstantProperties.mk (.integer (IntegerAttr.mk (-1) ctype))
  let (rewriter, cstOp) := rewriter.createOp! (.llvm .mlir__constant) #[op1.getType! rewriter.ctx.raw] #[]
    #[] #[] cstOpProp (some $ .before op)
  let (rewriter, newOp) := rewriter.createOp! (.llvm .xor) #[op1.getType! rewriter.ctx.raw] #[op1, (cstOp.getResult 0)]
    #[] #[] () (some $ .before op)
  return rewriter.replaceOp! op newOp

set_option warn.sorry false in
def right_identity_zero_0 (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (lhs, rhs, _props) := matchSub op rewriter.ctx | return rewriter
  let some cst := matchConstantIntVal rhs rewriter.ctx | return rewriter
  if cst.value ≠ 0 then return rewriter
  let rewriter := rewriter.replaceValue (op.getResult 0) lhs sorry sorry sorry
  rewriter.eraseOp op sorry sorry sorry

set_option warn.sorry false in
def right_identity_zero_1 (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (lhs, rhs, _props) := matchAdd op rewriter.ctx | return rewriter
  let some cst := matchConstantIntVal rhs rewriter.ctx | return rewriter
  if cst.value ≠ 0 then return rewriter
  let rewriter := rewriter.replaceValue (op.getResult 0) lhs sorry sorry sorry
  rewriter.eraseOp op sorry sorry sorry

set_option warn.sorry false in
def right_identity_zero_2 (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (lhs, rhs, _props) := matchOr op rewriter.ctx | return rewriter
  let some cst := matchConstantIntVal rhs rewriter.ctx | return rewriter
  if cst.value ≠ 0 then return rewriter
  let rewriter := rewriter.replaceValue (op.getResult 0) lhs sorry sorry sorry
  rewriter.eraseOp op sorry sorry sorry

set_option warn.sorry false in
def right_identity_zero_3 (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (lhs, rhs, _props) := matchXor op rewriter.ctx | return rewriter
  let some cst := matchConstantIntVal rhs rewriter.ctx | return rewriter
  if cst.value ≠ 0 then return rewriter
  let rewriter := rewriter.replaceValue (op.getResult 0) lhs sorry sorry sorry
  rewriter.eraseOp op sorry sorry sorry

set_option warn.sorry false in
def right_identity_zero_4 (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (lhs, rhs, _props) := matchShl op rewriter.ctx | return rewriter
  let some cst := matchConstantIntVal rhs rewriter.ctx | return rewriter
  if cst.value ≠ 0 then return rewriter
  let rewriter := rewriter.replaceValue (op.getResult 0) lhs sorry sorry sorry
  rewriter.eraseOp op sorry sorry sorry

set_option warn.sorry false in
def right_identity_zero_5 (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (lhs, rhs, _props) := matchAshr op rewriter.ctx | return rewriter
  let some cst := matchConstantIntVal rhs rewriter.ctx | return rewriter
  if cst.value ≠ 0 then return rewriter
  let rewriter := rewriter.replaceValue (op.getResult 0) lhs sorry sorry sorry
  rewriter.eraseOp op sorry sorry sorry

set_option warn.sorry false in
def right_identity_zero_6 (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (lhs, rhs, _props) := matchLshr op rewriter.ctx | return rewriter
  let some cst := matchConstantIntVal rhs rewriter.ctx | return rewriter
  if cst.value ≠ 0 then return rewriter
  let rewriter := rewriter.replaceValue (op.getResult 0) lhs sorry sorry sorry
  rewriter.eraseOp op sorry sorry sorry

set_option warn.sorry false in
def right_identity_one_int (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (x, rhs, _props) := matchMul op rewriter.ctx | return rewriter
  let some cst := matchConstantIntVal rhs rewriter.ctx | return rewriter
  if cst.value ≠ 1 then return rewriter
  let rewriter := rewriter.replaceValue (op.getResult 0) x sorry sorry sorry
  rewriter.eraseOp op sorry sorry sorry

set_option warn.sorry false in
def binop_same_val_0 (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (src, src1, _) := matchAnd op rewriter.ctx | return rewriter
  if src != src1 then return rewriter
  let rewriter := rewriter.replaceValue (op.getResult 0) src sorry sorry sorry
  rewriter.eraseOp op sorry sorry sorry

set_option warn.sorry false in
def binop_same_val_1 (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (src, src1, _props) := matchOr op rewriter.ctx | return rewriter
  if src != src1 then return rewriter
  let rewriter := rewriter.replaceValue (op.getResult 0) src sorry sorry sorry
  rewriter.eraseOp op sorry sorry sorry

def same_val_zero_0 (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (x, x1, _props) := matchSub op rewriter.ctx | return rewriter
  if x != x1 then return rewriter
  let .integerType type := (x.getType! rewriter.ctx.raw).val | return rewriter
  let cstProp := LLVMConstantProperties.mk (.integer (IntegerAttr.mk (0) type))
  let (rewriter, newOp) := rewriter.createOp! (.llvm .mlir__constant) #[x.getType! rewriter.ctx.raw] #[]
    #[] #[] cstProp (some $ .before op)
  return rewriter.replaceOp! op newOp

def same_val_zero_1 (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (x, x1, _props) := matchXor op rewriter.ctx | return rewriter
  if x != x1 then return rewriter
  let .integerType type := (x.getType! rewriter.ctx.raw).val | return rewriter
  let cstProp := LLVMConstantProperties.mk (.integer (IntegerAttr.mk (0) type))
  let (rewriter, newOp) := rewriter.createOp! (.llvm .mlir__constant) #[x.getType! rewriter.ctx.raw] #[]
    #[] #[] cstProp (some $ .before op)
  return rewriter.replaceOp! op newOp

set_option warn.sorry false in
def binop_right_to_zero (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (lhs, zero, _props) := matchMul op rewriter.ctx | return rewriter
  let some cst := matchConstantIntVal zero rewriter.ctx | return rewriter
  if cst.value ≠ 0 then return rewriter
  let rewriter := rewriter.replaceValue (op.getResult 0) zero sorry sorry sorry
  rewriter.eraseOp op sorry sorry sorry

def mul_by_neg_one (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (x, rhs, _props) := matchMul op rewriter.ctx | return rewriter
  let some cst := matchConstantIntVal rhs rewriter.ctx | return rewriter
  if cst.value ≠ -1 then return rewriter
  let .integerType ctype := (x.getType! rewriter.ctx.raw).val | return rewriter
  let cstOpProp := LLVMConstantProperties.mk (.integer (IntegerAttr.mk (0) ctype))
  let (rewriter, cstOp) := rewriter.createOp! (.llvm .mlir__constant) #[x.getType! rewriter.ctx.raw] #[]
    #[] #[] cstOpProp (some $ .before op)
  let (rewriter, newOp) := rewriter.createOp! (.llvm .sub) #[x.getType! rewriter.ctx.raw] #[(cstOp.getResult 0), x]
    #[] #[] _props (some $ .before op)
  return rewriter.replaceOp! op newOp

def or_and_xor_to_or (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (and, y, _props) := matchOr op rewriter.ctx | return rewriter
  let some defOp := getDefiningOp and rewriter.ctx | return rewriter
  let some (x, not, _) := matchAnd defOp rewriter.ctx | return rewriter
  let some defOp1 := getDefiningOp not rewriter.ctx | return rewriter
  let some (y1, rhs, _props1) := matchXor defOp1 rewriter.ctx | return rewriter
  if y != y1 then return rewriter
  let some cst := matchConstantIntVal rhs rewriter.ctx | return rewriter
  if cst.value ≠ -1 then return rewriter
  let (rewriter, newOp) := rewriter.createOp! (.llvm .or) #[and.getType! rewriter.ctx.raw] #[x, y]
    #[] #[] _props (some $ .before op)
  return rewriter.replaceOp! op newOp

def and_xor_or_to_and (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (or, y, _) := matchAnd op rewriter.ctx | return rewriter
  let some defOp := getDefiningOp or rewriter.ctx | return rewriter
  let some (x, not, _props) := matchOr defOp rewriter.ctx | return rewriter
  let some defOp1 := getDefiningOp not rewriter.ctx | return rewriter
  let some (y1, rhs, _props1) := matchXor defOp1 rewriter.ctx | return rewriter
  if y != y1 then return rewriter
  let some cst := matchConstantIntVal rhs rewriter.ctx | return rewriter
  if cst.value ≠ -1 then return rewriter
  let (rewriter, newOp) := rewriter.createOp! (.llvm .and) #[or.getType! rewriter.ctx.raw] #[x, y]
    #[] #[] () (some $ .before op)
  return rewriter.replaceOp! op newOp

set_option warn.sorry false in
def add_sub_reg_0 (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (x, tmp, _props) := matchAdd op rewriter.ctx | return rewriter
  let some defOp := getDefiningOp tmp rewriter.ctx | return rewriter
  let some (src, x1, _props1) := matchSub defOp rewriter.ctx | return rewriter
  if x != x1 then return rewriter
  let rewriter := rewriter.replaceValue (op.getResult 0) src sorry sorry sorry
  rewriter.eraseOp op sorry sorry sorry

set_option warn.sorry false in
def add_sub_reg_1 (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (tmp, x, _props) := matchAdd op rewriter.ctx | return rewriter
  let some defOp := getDefiningOp tmp rewriter.ctx | return rewriter
  let some (src, x1, _props1) := matchSub defOp rewriter.ctx | return rewriter
  if x != x1 then return rewriter
  let rewriter := rewriter.replaceValue (op.getResult 0) src sorry sorry sorry
  rewriter.eraseOp op sorry sorry sorry

def APlusBMinusCMinusB (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (add1, B, _props) := matchSub op rewriter.ctx | return rewriter
  let some defOp := getDefiningOp add1 rewriter.ctx | return rewriter
  let some (A, sub1, _props1) := matchAdd defOp rewriter.ctx | return rewriter
  let some defOp1 := getDefiningOp sub1 rewriter.ctx | return rewriter
  let some (B1, C, _props2) := matchSub defOp1 rewriter.ctx | return rewriter
  if B != B1 then return rewriter
  let (rewriter, newOp) := rewriter.createOp! (.llvm .sub) #[add1.getType! rewriter.ctx.raw] #[A, C]
    #[] #[] _props (some $ .before op)
  return rewriter.replaceOp! op newOp

def AMinusBMinusCMinusC (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (sub2, C, _props) := matchSub op rewriter.ctx | return rewriter
  let some defOp := getDefiningOp sub2 rewriter.ctx | return rewriter
  let some (A, sub1, _props1) := matchSub defOp rewriter.ctx | return rewriter
  let some defOp1 := getDefiningOp sub1 rewriter.ctx | return rewriter
  let some (B, C1, _props2) := matchSub defOp1 rewriter.ctx | return rewriter
  if C != C1 then return rewriter
  let (rewriter, newOp) := rewriter.createOp! (.llvm .sub) #[sub2.getType! rewriter.ctx.raw] #[A, B]
    #[] #[] _props (some $ .before op)
  return rewriter.replaceOp! op newOp

def ZeroMinusAPlusB (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (sub, B, _props) := matchAdd op rewriter.ctx | return rewriter
  let some defOp := getDefiningOp sub rewriter.ctx | return rewriter
  let some (lhs, A, _props1) := matchSub defOp rewriter.ctx | return rewriter
  let some cst := matchConstantIntVal lhs rewriter.ctx | return rewriter
  if cst.value ≠ 0 then return rewriter
  let (rewriter, newOp) := rewriter.createOp! (.llvm .sub) #[sub.getType! rewriter.ctx.raw] #[B, A]
    #[] #[] _props (some $ .before op)
  return rewriter.replaceOp! op newOp

def APlusZeroMinusB (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (A, sub, _props) := matchAdd op rewriter.ctx | return rewriter
  let some defOp := getDefiningOp sub rewriter.ctx | return rewriter
  let some (lhs, B, _props1) := matchSub defOp rewriter.ctx | return rewriter
  let some cst := matchConstantIntVal lhs rewriter.ctx | return rewriter
  if cst.value ≠ 0 then return rewriter
  let (rewriter, newOp) := rewriter.createOp! (.llvm .sub) #[A.getType! rewriter.ctx.raw] #[A, B]
    #[] #[] _props (some $ .before op)
  return rewriter.replaceOp! op newOp

set_option warn.sorry false in
def APlusBMinusB (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (A, sub, _props) := matchAdd op rewriter.ctx | return rewriter
  let some defOp := getDefiningOp sub rewriter.ctx | return rewriter
  let some (B, A1, _props1) := matchSub defOp rewriter.ctx | return rewriter
  if A != A1 then return rewriter
  let rewriter := rewriter.replaceValue (op.getResult 0) B sorry sorry sorry
  rewriter.eraseOp op sorry sorry sorry

set_option warn.sorry false in
def BMinusAPlusA (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (sub, A, _props) := matchAdd op rewriter.ctx | return rewriter
  let some defOp := getDefiningOp sub rewriter.ctx | return rewriter
  let some (B, A1, _props1) := matchSub defOp rewriter.ctx | return rewriter
  if A != A1 then return rewriter
  let rewriter := rewriter.replaceValue (op.getResult 0) B sorry sorry sorry
  rewriter.eraseOp op sorry sorry sorry

def AMinusBPlusCMinusA (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (sub1, sub2, _props) := matchAdd op rewriter.ctx | return rewriter
  let some defOp := getDefiningOp sub1 rewriter.ctx | return rewriter
  let some (A, B, _props1) := matchSub defOp rewriter.ctx | return rewriter
  let some defOp1 := getDefiningOp sub2 rewriter.ctx | return rewriter
  let some (C, A1, _props2) := matchSub defOp1 rewriter.ctx | return rewriter
  if A != A1 then return rewriter
  let (rewriter, newOp) := rewriter.createOp! (.llvm .sub) #[sub1.getType! rewriter.ctx.raw] #[C, B]
    #[] #[] _props (some $ .before op)
  return rewriter.replaceOp! op newOp

def AMinusBPlusBMinusC (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (sub1, sub2, _props) := matchAdd op rewriter.ctx | return rewriter
  let some defOp := getDefiningOp sub1 rewriter.ctx | return rewriter
  let some (A, B, _props1) := matchSub defOp rewriter.ctx | return rewriter
  let some defOp1 := getDefiningOp sub2 rewriter.ctx | return rewriter
  let some (B1, C, _props2) := matchSub defOp1 rewriter.ctx | return rewriter
  if B != B1 then return rewriter
  let (rewriter, newOp) := rewriter.createOp! (.llvm .sub) #[sub1.getType! rewriter.ctx.raw] #[A, C]
    #[] #[] _props (some $ .before op)
  return rewriter.replaceOp! op newOp

def APlusBMinusAplusC (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (A, sub1, _props) := matchAdd op rewriter.ctx | return rewriter
  let some defOp := getDefiningOp sub1 rewriter.ctx | return rewriter
  let some (B, add1, _props1) := matchSub defOp rewriter.ctx | return rewriter
  let some defOp1 := getDefiningOp add1 rewriter.ctx | return rewriter
  let some (A1, C, _props2) := matchAdd defOp1 rewriter.ctx | return rewriter
  if A != A1 then return rewriter
  let (rewriter, newOp) := rewriter.createOp! (.llvm .sub) #[A.getType! rewriter.ctx.raw] #[B, C]
    #[] #[] _props (some $ .before op)
  return rewriter.replaceOp! op newOp

def APlusBMinusCPlusA (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (A, sub1, _props) := matchAdd op rewriter.ctx | return rewriter
  let some defOp := getDefiningOp sub1 rewriter.ctx | return rewriter
  let some (B, add1, _props1) := matchSub defOp rewriter.ctx | return rewriter
  let some defOp1 := getDefiningOp add1 rewriter.ctx | return rewriter
  let some (C, A1, _props2) := matchAdd defOp1 rewriter.ctx | return rewriter
  if A != A1 then return rewriter
  let (rewriter, newOp) := rewriter.createOp! (.llvm .sub) #[A.getType! rewriter.ctx.raw] #[B, C]
    #[] #[] _props (some $ .before op)
  return rewriter.replaceOp! op newOp

def AMinusZeroMinusB (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (A, sub1, _props) := matchSub op rewriter.ctx | return rewriter
  let some defOp := getDefiningOp sub1 rewriter.ctx | return rewriter
  let some (lhs, B, _props1) := matchSub defOp rewriter.ctx | return rewriter
  let some cst := matchConstantIntVal lhs rewriter.ctx | return rewriter
  if cst.value ≠ 0 then return rewriter
  let (rewriter, newOp) := rewriter.createOp! (.llvm .add) #[A.getType! rewriter.ctx.raw] #[A, B]
    #[] #[] _props (some $ .before op)
  return rewriter.replaceOp! op newOp

set_option warn.sorry false in
def AMinusBMinusA (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) := do
  let some (A, add, _props) := matchSub op rewriter.ctx | return rewriter
  let some defOp := getDefiningOp add rewriter.ctx | return rewriter
  let some (A1, B, _props1) := matchSub defOp rewriter.ctx | return rewriter
  if A != A1 then return rewriter
  let rewriter := rewriter.replaceValue (op.getResult 0) B sorry sorry sorry
  rewriter.eraseOp op sorry sorry sorry

def mir_pattern_combines :=
  [sub_minus_one,
  right_identity_zero_0,
  right_identity_zero_1,
  right_identity_zero_2,
  right_identity_zero_3,
  right_identity_zero_4,
  right_identity_zero_5,
  right_identity_zero_6,
  right_identity_one_int,
  binop_same_val_0,
  binop_same_val_1,
  same_val_zero_0,
  same_val_zero_1,
  binop_right_to_zero,
  mul_by_neg_one,
  or_and_xor_to_or,
  and_xor_or_to_and,
  add_sub_reg_0,
  add_sub_reg_1,
  APlusBMinusCMinusB,
  AMinusBMinusCMinusC,
  ZeroMinusAPlusB,
  APlusZeroMinusB,
  APlusBMinusB,
  BMinusAPlusA,
  AMinusBPlusCMinusA,
  AMinusBPlusBMinusC,
  APlusBMinusAplusC,
  APlusBMinusCPlusA,
  AMinusZeroMinusB,
  AMinusBMinusA]

end Veir.RISCV