name: Build Documentation

on:
  push:
  pull_request:
  workflow_dispatch:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the project
        uses: leanprover/lean-action@v1
        with:
          lake-package-directory: "docgen"
          build-args: "Veir:docs"
