name: Build Documentation

on:
  push:
  pull_request:
  workflow_dispatch:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the project
        uses: leanprover/lean-action@v1
        with:
          lake-package-directory: "docbuild"
          build-args: "Veir:docs"

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: build_outputs_folder/
