name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - name: "Change directory"
        run:  cd docgen

      - name: Build the project
        uses: leanprover/lean-action@v1
        with:
          build-args: "--iofail Veir:docs"
